### ISSUE TITLE
Custom acme.sh options possible

### ISSUE THREAD

**Issue by mastermueller** [Neilpang/letsproxy#12]
Hi!
It would be great to be able to influence the acme.sh execution options, for example change the method to DNS-01 instead of HTTP-01.
Is something like this planned in the future?

**Comment by neilpang** [comment]
not yet.

**Comment by neilpang** [comment]
read this link if you are using docker:
https://github.com/acmesh-official/acme.sh/wiki/Run-acme.sh-in-docker
