### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by imp1sh** [Neilpang/letsproxy#9]
I'm trying to deploy this with podman, which is daemon-less, so there is no docker.sock as well as no podman.sock file in /var/run.
What is the purpose of this volume, anyhow? Is there a prospect of using this on podman some day?

**Comment by neilpang** [comment]
see the base project: https://github.com/nginx-proxy/nginx-proxy

If the base project supports podman,   then we can support it.

**Comment by imp1sh** [comment]
There is this Q/A: https://github.com/nginx-proxy/nginx-proxy/discussions/1845
I will try, thank you.
